WebApplication2/Controllers/BPsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class BPsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BPsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: BPs
        public async Task<IActionResult> Index()
        {
            return View(await _context.BP.ToListAsync());
        }

        // GET: BPs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bP = await _context.BP
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bP == null)
            {
                return NotFound();
            }

            return View(bP);
        }

        // GET: BPs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BP bP, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    bP.TitleImagePath = titleImageFile.FileName;
                    using var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "img/BP_img/", titleImageFile.FileName), FileMode.Create);
                    titleImageFile.CopyTo(stream);
                }
                _context.Add(bP);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bP);
        }

        // GET: BPs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bP = await _context.BP.FindAsync(id);
            if (bP == null)
            {
                return NotFound();
            }
            return View(bP);
        }

        // POST: BPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BP bP, IFormFile titleImageFile)
        {
            if (id != bP.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bP);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BPExists(bP.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bP);
        }

        // GET: BPs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bP = await _context.BP
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bP == null)
            {
                return NotFound();
            }

            return View(bP);
        }

        // POST: BPs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bP = await _context.BP.FindAsync(id);
            _context.BP.Remove(bP);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BPExists(int id)
        {
            return _context.BP.Any(e => e.Id == id);
        }
    }
}

WebApplication2/Controllers/CPUsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Hosting.Internal;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CPUsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public CPUsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: CPUs
        public async Task<IActionResult> Index()
        {
            return View(await _context.CPU.ToListAsync());
        }

        // GET: CPUs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cPU = await _context.CPU
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cPU == null)
            {
                return NotFound();
            }

            return View(cPU);
        }

        // GET: CPUs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CPUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CPU cPU,IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    cPU.TitleImagePath = titleImageFile.FileName;
                    using var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "img/CPU_img/", titleImageFile.FileName), FileMode.Create);
                    titleImageFile.CopyTo(stream);
                }
                _context.Add(cPU);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cPU);
        }

        // GET: CPUs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cPU = await _context.CPU.FindAsync(id);
            if (cPU == null)
            {
                return NotFound();
            }
            return View(cPU);
        }

        // POST: CPUs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CPU cPU, IFormFile titleImageFile)
        {
            if (id != cPU.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (titleImageFile != null)
                    {
                        cPU.TitleImagePath = titleImageFile.FileName;
                        using var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "img/CPU_img/", titleImageFile.FileName), FileMode.Create);
                        titleImageFile.CopyTo(stream);
                    }
                    _context.Update(cPU);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CPUExists(cPU.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cPU);
        }

        // GET: CPUs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cPU = await _context.CPU
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cPU == null)
            {
                return NotFound();
            }

            return View(cPU);
        }

        // POST: CPUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cPU = await _context.CPU.FindAsync(id);
            _context.CPU.Remove(cPU);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CPUExists(int id)
        {
            return _context.CPU.Any(e => e.Id == id);
        }
    }
}

WebApplication2/Controllers/DVDsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class DVDsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public DVDsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: DVDs
        public async Task<IActionResult> Index()
        {
            return View(await _context.DVD.ToListAsync());
        }

        // GET: DVDs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dVD = await _context.DVD
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dVD == null)
            {
                return NotFound();
            }

            return View(dVD);
        }

        // GET: DVDs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DVDs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( DVD dVD, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    dVD.TitleImagePath = titleImageFile.FileName;
                    using var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "img/DVD_img/", titleImageFile.FileName), FileMode.Create);
                    titleImageFile.CopyTo(stream);
                }
                _context.Add(dVD);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dVD);
        }

        // GET: DVDs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dVD = await _context.DVD.FindAsync(id);
            if (dVD == null)
            {
                return NotFound();
            }
            return View(dVD);
        }

        // POST: DVDs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, DVD dVD, IFormFile titleImageFile)
        {
            if (id != dVD.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (titleImageFile != null)
                    {
                        dVD.TitleImagePath = titleImageFile.FileName;
                        using var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "img/DVD_img/", titleImageFile.FileName), FileMode.Create);
                        titleImageFile.CopyTo(stream);
                    }
                    _context.Update(dVD);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DVDExists(dVD.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dVD);
        }

        // GET: DVDs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dVD = await _context.DVD
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dVD == null)
            {
                return NotFound();
            }

            return View(dVD);
        }

        // POST: DVDs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dVD = await _context.DVD.FindAsync(id);
            _context.DVD.Remove(dVD);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DVDExists(int id)
        {
            return _context.DVD.Any(e => e.Id == id);
        }
    }
}

WebApplication2/Views/Home/All.cshtml
@{
    Layout = "_Layout_2";
}
<div id="comp-icontb" class="iconbox">
    <div class="icontb">
        <div class="tr">
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Home" asp-action="All_Сonfigurator">
					<div>
						<img src="~/img/confg-ico-20.svg" alt="">
						<div class="td_text">Супер Конфигуратор</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Finished_assembly" asp-action="Index">
					<div>
						<img src="~/img/icon_part/icob-btn-08.svg" alt="">
						<div class="td_text">Дайын жиынтықтар</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Home" asp-action="All_Periphery">
					<div>
						<img src="~/img/icon_part/icob-btn-08.svg" alt="">
						<div class="td_text">Периферия</div>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>

WebApplication2/Views/Home/All_Finished_assembly.cshtml
<	@{
    Layout = "_Layout_2";
}
	div id="comp-icontb" class="iconbox">
    <div class="icontb">
        <div class="tr">
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Finished_assembly" asp-action="Index">
					<div>
						<img src="~/img/icon_part/icob-btn-08.svg" alt="">
						<div class="td_text">Периферия</div>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>

WebApplication2/Views/Home/All_Periphery.cshtml
@{
	Layout = "_Layout_2";
}
<div id="comp-icontb" class="iconbox">
    <div class="icontb">
        <div class="tr">
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Monitors" asp-action="Index">
					<div>
						<img src="~/img/confg-ico-9.svg" alt="">
						<div class="td_text">Монитор</div>
					</div>
				</a>
			</div>
			
			<div class="td btltbox btltbox-vd"> 
				<a asp-controller="Keyboards" asp-action="Index">
					<div >
						<img src="~/img/confg-ico-11.svg" alt="">
						<div class="td_text">Пернетақта</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd"> 
				<a asp-controller="Mice" asp-action="Index">
					<div >					
						<img src="~/img/confg-ico-10.svg" alt="">
						<div class="td_text">Тышқан</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Mouse_pads" asp-action="Index">
					<div>
						<img src="~/img/confg-ico-mouse-pad.svg" alt="">
						<div class="td_text">Коврик</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Headphones" asp-action="Index">
					<div>
						<img src="~/img/confg-ico-headphones.svg" alt="">
						<div class="td_text">Құлаққап</div>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>

WebApplication2/Views/Home/All_Сonfigurator.cshtml
@{
	Layout = "_Layout_2";
}
<div id="comp-icontb" class="iconbox">
    <div class="icontb">
        <div class="tr">
			<div class="td btltbox btltbox-vd">
				<a asp-controller="CPUs" asp-action="Index">
					<div>
						<img src="~/img/icon_part/confg-ico-1.svg" alt="">
						<div class="td_text">Процессор</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Matplatas" asp-action="Index">
					<div>
						<img src="~/img/icon_part/confg-ico-2.svg" alt="">
						<div class="td_text">Аналық плата</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd">
				<a asp-controller="RAMs" asp-action="Index">
					<div>
						<img src="~/img/icon_part/confg-ico-4.svg" alt="">
						<div class="td_text">Жедел жады</div>
					</div>
				</a>
			</div>
			
			<div class="td btltbox btltbox-vd">
				<a asp-controller="BPs" asp-action="Index">
					<div > 
						<img src="~/img/icon_part/confg-ico-5.svg" alt="">
						<div class="td_text">Қуат блогы</div>
				  	</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd"> 
				<a asp-controller="Cases" asp-action="Index">
					<div > 
						<img src="~/img/icon_part/confg-ico-8.svg" alt="">
						<div class="td_text">Корпус</div>
				   	</div>
				</a>
			</div>
			
		</div>
        <div class="tr">
			<div class="td btltbox btltbox-vd">
				<a asp-controller="Coolers" asp-action="Index">
					<div>
						<img src="~/img/icon_part/icob-btn-02.svg" alt="">
						<div class="td_text">Салқындатқыш</div>
					</div>
				</a>
			</div>
			
			<div class="td btltbox btltbox-vd">
				<a asp-controller="CoolingSystems" asp-action="Index">
					<div>
						<img src="~/img/icon_part/confg-ico-6.svg" alt="">
						<div class="td_text">Суыту жүйесі</div>
				   	</div>
				</a>
			</div>
			
			<div class="td btltbox btltbox-vd"> 
				<a asp-controller="DVDs" asp-action="Index">
					<div >
						<img src="~/img/icon_part/111.png" alt="">
						<div class="td_text">DVD слот</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd"> 
				<a asp-controller="GPUs" asp-action="Index">
					<div>	 				
						<img src="~/img/icon_part/icob-btn-05.svg" alt="">
						<div class="td_text">Графикалық карта</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd">
				<a asp-controller="NetworkCards" asp-action="Index">
					<div>
						<img src="~/img/icon_part/1.png" alt="">
						<div class="td_text">Желілік карта</div>
					</div>
				</a>
			</div>
			
		</div>
        <div class="tr">
			<div class="td btltbox btltbox-vd">
				<a asp-controller="ColvoMemories" asp-action="Index">
					<div>
						<img src="~/img/icon_part/confg-ico-4.svg" alt="">
						<div class="td_text">Жады саны</div>
					</div>
				</a>
			</div>
			
			<div class="td btltbox btltbox-vd"> 
				<a asp-controller="TypeOfMemories" asp-action="Index">
					<div >
						<img src="~/img/icon_part/icob-btn-06.svg" alt="">
						<div class="td_text">Жады түрі</div>
					</div>
				</a>
			</div>
			<div class="td btltbox btltbox-vd"> 
				<a asp-controller="VoiceCards" asp-action="Index">
					<div >					
						<img src="~/img/icon_part/11.png" alt="">
						<div class="td_text">Дыбыс картасы</div>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>

WebApplication2/Views/Home/Cities.cshtml
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>

<div class="b-nrp-config-meta">
    <h1 class="b-page-header">Сборка компьютера по каталогам интернет-магазинов</h1>
</div>
<!-- Example Code -->

<p>
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="true" aria-controls="collapseExample"
       style="margin: 0 170px 0 170px; text-align: inherit; background-color: #dce6f1; border-color: #bbb; user-select: none; color: rgba(27, 27, 29, 0.5);font-weight: 700;font-size: 20px;line-height: 1.3;position: relative;padding: 12px 30px 12px 60px;cursor: pointer;">
        <img src="../img/nostr.svg" alt=""> Быстрый подбор ПК  <img src="../img/указатель.svg" style="margin: 0 30px 0 825px;">
    </a>
</p>
<div class="collapse show" id="collapseExample" style="">
    <div class="card card-body" style="background-color: #dce6f1;">
        <div class="b-cfgfw-body">
            <div class="b-cfgfw-select-form">
                <div class="b-form-group">
                    <div class="b-label">выберите бюджет пк, <b class="red_text">$</b></div>
                    <div class="range-wrapper">
                        <div class="price-input">
                            <div class="values">
                                <span id="range1">
                                    0
                                </span>
                                <span> &dash; </span>
                                <span id="range2">
                                    100
                                </span>
                            </div>
                            <div class="container">
                                <div class="slider-track"></div>
                                <input type="range" min="0" max="10000" value="0" id="slider-1" oninput="slideOne()">
                                <input type="range" min="0" max="10000" value="10000" id="slider-2" oninput="slideTwo()">
                            </div>
                                <script>

                                window.onload = function () {
                                    slideOne();
                                    slideTwo();
                                }
                                let sliderOne = document.getElementById("slider-1");
                                let sliderTwo = document.getElementById("slider-2");
                                let displayValOne = document.getElementById("range1");
                                let displayValTwo = document.getElementById("range2");
                                let minGap = 0;
                                let sliderTrack = document.querySelector(".slider-track");
                                let sliderMaxValue = document.getElementById("slider-1").max;
                                function slideOne() {
                                    if (parseInt(sliderTwo.value) - parseInt(sliderOne.value) <= minGap) {
                                        sliderOne.value = parseInt(sliderTwo.value) - minGap;
                                    }
                                    displayValOne.textContent = sliderOne.value+'$';
                                    fillColor();
                                }
                                function slideTwo() {
                                    if (parseInt(sliderTwo.value) - parseInt(sliderOne.value) <= minGap) {
                                        sliderTwo.value = parseInt(sliderOne.value) + minGap;
                                    }
                                    displayValTwo.textContent = sliderTwo.value+'$';
                                    fillColor();
                                }
                                function fillColor() {
                                    percent1 = (sliderOne.value / sliderMaxValue) * 100;
                                    percent2 = (sliderTwo.value / sliderMaxValue) * 100;
                                    sliderTrack.style.background = `linear-gradient(to right, #dadae5 ${percent1}% , #313645 ${percent1}% , #313645 ${percent2}%, #dadae5 ${percent2}%)`;
                                }
                                </script>
                                </div>
                    </div>
                    <div class="b-form-group">
                        <div class="b-label">Выберите назначение</div>
                        <div class="b-form-field">
                            <ul class="b-list-cfg-params">
                                <li>
                                    <input type="radio" id="cfgGaming" name="dest" checked="checked" value="game">
                                    <label for="cfgGaming">
                                        <span class="b-ico">
                                            <img src="../img/ico-cfg-gaming.svg" alt="">
                                        </span>
                                        <span class="b-txt">Для гейминга</span>
                                    </label>
                                </li>
                                <li>
                                    <input type="radio" id="cfgBusiness" name="dest" value="work">
                                    <label for="cfgBusiness">
                                        <span class="b-ico">
                                            <img src="../img/ico-cfg-business.svg" alt="">
                                        </span>
                                        <span class="b-txt">Для работы</span>
                                    </label>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="b-form-group">
                        <div class="b-label">Предпочтения по марке</div>
                        <div class="b-form-field">
                            <ul class="b-list-cfg-params">
                                <li>
                                    <input type="radio" id="cfgAMD" name="manufactor" checked="checked" value="amd">
                                    <label for="cfgAMD">
                                        <span class="b-ico">
                                            <img src="../img/image-cfg-amd.png" alt="">
                                        </span>
                                    </label>
                                </li>
                                <li>
                                    <input type="radio" id="cfgIntel" name="manufactor" value="intel">
                                    <label for="cfgIntel">
                                        <span class="b-ico">
                                            <img src="../img/image-cfg-intel.png" alt="">
                                        </span>
                                    </label>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <button class="b-btn-get-started">подобрать компьютер</button>
                </div>
            </div>
        </div>
    </div>
</div>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>*@

WebApplication2/Views/Home/Index.cshtml
  <div class="block">
    
    <div class="block_left">
      <div>
      <div class="square">
        <div class="square__bg-wrap" style="background-color: #0376c5;" > 
            <div class="square__bg "
          style="background-image: url('https://i.pinimg.com/originals/03/dd/d1/03ddd10eae09ddb201060c7d7d630b06.jpg')">
        </div>
        </div> 
        </div>
      <div class="text">Выберите готовый компьютер из наших качественных сборok </div>
      </div>
      
         <div> 
           <div class="text">Соберите Персональный компьютер под ваш вкус и бюджет</div>
            <div class="square">
                <div class="square__bg-wrap" style="background-color: #445599;"> 
              <div class="square__bg" style="background-image: url('https://i.pinimg.com/originals/9d/0a/59/9d0a59174cbddce8c8da59797de9c672.jpg')"></div>
                </div> 
          </div>
    </div>
      
    </div>
    <div class="block_right">
       <h1 class="title">
       Создадим ПК <br/> вашей мечты
       </h1>

       <div class="buttons">
            <a asp-controller="Home" asp-action="Cities" class="button-bistriy" style="display:none"><img src="/img/молния.svg"> Готовая сборка</a>
   			<a asp-controller="Home" asp-action="Qwerty" class="button-sobrat"> <img src="/img/ключ.svg"> Собрать компьютер</a>
	    </div>
    </div>
</div>