WebApplication2/Models/GPU.cs
using System.Collections.Generic;

namespace WebApplication2.Models
{
    public class GPU
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public ushort Price { get; set; }

        public virtual string TitleImagePath { get; set; }

        public string Desc { get; set; }

        public int Memory { get; set; }

        public string TypeOfMemory { get; set; }


        public List<Finished_assembly> Finished_assembly { get; set; }
    }
}

WebApplication2/Controllers/GPUsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class GPUsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public GPUsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: GPUs
        public async Task<IActionResult> Index()
        {
            return View(await _context.VideoCard.ToListAsync());
        }

        // GET: GPUs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gPU = await _context.VideoCard
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gPU == null)
            {
                return NotFound();
            }

            return View(gPU);
        }

        // GET: GPUs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GPUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( GPU gPU, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    gPU.TitleImagePath = titleImageFile.FileName;
                    using var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "img/GPU_img/", titleImageFile.FileName), FileMode.Create);
                    titleImageFile.CopyTo(stream);
                }
                _context.Add(gPU);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gPU);
        }

        // GET: GPUs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gPU = await _context.VideoCard.FindAsync(id);
            if (gPU == null)
            {
                return NotFound();
            }
            return View(gPU);
        }

        // POST: GPUs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, GPU gPU, IFormFile titleImageFile)
        {
            if (id != gPU.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (titleImageFile != null)
                    {
                        gPU.TitleImagePath = titleImageFile.FileName;
                        using var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "img/GPU_img/", titleImageFile.FileName), FileMode.Create);
                        titleImageFile.CopyTo(stream);
                    }
                    _context.Update(gPU);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GPUExists(gPU.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gPU);
        }

        // GET: GPUs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gPU = await _context.VideoCard
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gPU == null)
            {
                return NotFound();
            }

            return View(gPU);
        }

        // POST: GPUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gPU = await _context.VideoCard.FindAsync(id);
            _context.VideoCard.Remove(gPU);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GPUExists(int id)
        {
            return _context.VideoCard.Any(e => e.Id == id);
        }
    }
}

WebApplication2/Views/GPUs/Create.cshtml
@model WebApplication2.Models.GPU

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>GPU</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="" asp-controller="GPUs" asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
            </div>
            <div class="form-group">
                <label asp-for="Desc" class="control-label"></label>
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Memory" class="control-label"></label>
                <input asp-for="Memory" class="form-control" />
                <span asp-validation-for="Memory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfMemory" class="control-label"></label>
                <input asp-for="TypeOfMemory" class="form-control" />
                <span asp-validation-for="TypeOfMemory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication2/Views/GPUs/Delete.cshtml
@model WebApplication2.Models.GPU

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GPU</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TitleImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TitleImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Memory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Memory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfMemory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfMemory)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication2/Views/GPUs/Details.cshtml
@model WebApplication2.Models.GPU

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>GPU</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TitleImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TitleImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Memory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Memory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfMemory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfMemory)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication2/Views/GPUs/Edit.cshtml
@model WebApplication2.Models.GPU

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>GPU</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-area="" asp-controller="GPUs" asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
            </div>
            <div class="form-group">
                <label asp-for="Desc" class="control-label"></label>
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Memory" class="control-label"></label>
                <input asp-for="Memory" class="form-control" />
                <span asp-validation-for="Memory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfMemory" class="control-label"></label>
                <input asp-for="TypeOfMemory" class="form-control" />
                <span asp-validation-for="TypeOfMemory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication2/Views/GPUs/Index.cshtml
@model IEnumerable<WebApplication2.Models.GPU>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create"><button type="button" class="btn btn-info">Create New</button></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TitleImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Memory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeOfMemory)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
                <td>
                    <img src="~/CPU_img/@item.TitleImagePath">
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Desc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfMemory)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id"><button type="button" class="btn btn-primary">Edit</button></a> |
                    <a asp-action="Details" asp-route-id="@item.Id"><button type="button" class="btn btn-secondary">Details</button></a> |
                    <a asp-action="Delete" asp-route-id="@item.Id"><button type="button" class="btn btn-danger">Delete</button></a>
            </td>
        </tr>
}
    </tbody>
</table>
<p>
    <a asp-controller="Home" asp-action="All"><button type="button" class="btn btn-dark">Create New</button></a>
</p>